# CMake generated Testfile for 
# Source directory: D:/fdlang
# Build directory: D:/fdlang
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ASTManualTest" "D:/fdlang/Debug/test_ast_manual.exe")
  set_tests_properties("ASTManualTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;99;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ASTManualTest" "D:/fdlang/Release/test_ast_manual.exe")
  set_tests_properties("ASTManualTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;99;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("ASTManualTest" "D:/fdlang/MinSizeRel/test_ast_manual.exe")
  set_tests_properties("ASTManualTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;99;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ASTManualTest" "D:/fdlang/RelWithDebInfo/test_ast_manual.exe")
  set_tests_properties("ASTManualTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;99;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("ASTManualTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("LexerTest" "D:/fdlang/Debug/test_lexer.exe")
  set_tests_properties("LexerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;111;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("LexerTest" "D:/fdlang/Release/test_lexer.exe")
  set_tests_properties("LexerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;111;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("LexerTest" "D:/fdlang/MinSizeRel/test_lexer.exe")
  set_tests_properties("LexerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;111;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("LexerTest" "D:/fdlang/RelWithDebInfo/test_lexer.exe")
  set_tests_properties("LexerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;111;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("LexerTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ParserTest" "D:/fdlang/Debug/test_parser.exe")
  set_tests_properties("ParserTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;124;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ParserTest" "D:/fdlang/Release/test_parser.exe")
  set_tests_properties("ParserTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;124;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("ParserTest" "D:/fdlang/MinSizeRel/test_parser.exe")
  set_tests_properties("ParserTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;124;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ParserTest" "D:/fdlang/RelWithDebInfo/test_parser.exe")
  set_tests_properties("ParserTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;124;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("ParserTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ResolverTest" "D:/fdlang/Debug/test_resolver.exe")
  set_tests_properties("ResolverTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;140;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ResolverTest" "D:/fdlang/Release/test_resolver.exe")
  set_tests_properties("ResolverTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;140;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("ResolverTest" "D:/fdlang/MinSizeRel/test_resolver.exe")
  set_tests_properties("ResolverTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;140;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ResolverTest" "D:/fdlang/RelWithDebInfo/test_resolver.exe")
  set_tests_properties("ResolverTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;140;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("ResolverTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("DiagnosticTest" "D:/fdlang/Debug/test_diagnostic.exe")
  set_tests_properties("DiagnosticTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;151;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("DiagnosticTest" "D:/fdlang/Release/test_diagnostic.exe")
  set_tests_properties("DiagnosticTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;151;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("DiagnosticTest" "D:/fdlang/MinSizeRel/test_diagnostic.exe")
  set_tests_properties("DiagnosticTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;151;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("DiagnosticTest" "D:/fdlang/RelWithDebInfo/test_diagnostic.exe")
  set_tests_properties("DiagnosticTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;151;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("DiagnosticTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("TypeCheckerTest" "D:/fdlang/Debug/test_typechecker.exe")
  set_tests_properties("TypeCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;171;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("TypeCheckerTest" "D:/fdlang/Release/test_typechecker.exe")
  set_tests_properties("TypeCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;171;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("TypeCheckerTest" "D:/fdlang/MinSizeRel/test_typechecker.exe")
  set_tests_properties("TypeCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;171;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("TypeCheckerTest" "D:/fdlang/RelWithDebInfo/test_typechecker.exe")
  set_tests_properties("TypeCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;171;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("TypeCheckerTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("CFGTest" "D:/fdlang/Debug/test_cfg.exe")
  set_tests_properties("CFGTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;185;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("CFGTest" "D:/fdlang/Release/test_cfg.exe")
  set_tests_properties("CFGTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;185;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("CFGTest" "D:/fdlang/MinSizeRel/test_cfg.exe")
  set_tests_properties("CFGTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;185;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("CFGTest" "D:/fdlang/RelWithDebInfo/test_cfg.exe")
  set_tests_properties("CFGTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;185;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("CFGTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("MVIRGeneratorTest" "D:/fdlang/Debug/test_mvir_generator.exe")
  set_tests_properties("MVIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;205;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("MVIRGeneratorTest" "D:/fdlang/Release/test_mvir_generator.exe")
  set_tests_properties("MVIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;205;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("MVIRGeneratorTest" "D:/fdlang/MinSizeRel/test_mvir_generator.exe")
  set_tests_properties("MVIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;205;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("MVIRGeneratorTest" "D:/fdlang/RelWithDebInfo/test_mvir_generator.exe")
  set_tests_properties("MVIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;205;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("MVIRGeneratorTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("BorrowCheckerTest" "D:/fdlang/Debug/test_borrow_checker.exe")
  set_tests_properties("BorrowCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;226;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("BorrowCheckerTest" "D:/fdlang/Release/test_borrow_checker.exe")
  set_tests_properties("BorrowCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;226;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("BorrowCheckerTest" "D:/fdlang/MinSizeRel/test_borrow_checker.exe")
  set_tests_properties("BorrowCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;226;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("BorrowCheckerTest" "D:/fdlang/RelWithDebInfo/test_borrow_checker.exe")
  set_tests_properties("BorrowCheckerTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;226;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("BorrowCheckerTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("LLVMIRGeneratorTest" "D:/fdlang/Debug/test_llvmir_generator.exe")
  set_tests_properties("LLVMIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;248;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("LLVMIRGeneratorTest" "D:/fdlang/Release/test_llvmir_generator.exe")
  set_tests_properties("LLVMIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;248;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("LLVMIRGeneratorTest" "D:/fdlang/MinSizeRel/test_llvmir_generator.exe")
  set_tests_properties("LLVMIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;248;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("LLVMIRGeneratorTest" "D:/fdlang/RelWithDebInfo/test_llvmir_generator.exe")
  set_tests_properties("LLVMIRGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;248;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("LLVMIRGeneratorTest" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ExecutableGeneratorTest" "D:/fdlang/Debug/test_executable_generator.exe")
  set_tests_properties("ExecutableGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;273;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ExecutableGeneratorTest" "D:/fdlang/Release/test_executable_generator.exe")
  set_tests_properties("ExecutableGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;273;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("ExecutableGeneratorTest" "D:/fdlang/MinSizeRel/test_executable_generator.exe")
  set_tests_properties("ExecutableGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;273;add_test;D:/fdlang/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ExecutableGeneratorTest" "D:/fdlang/RelWithDebInfo/test_executable_generator.exe")
  set_tests_properties("ExecutableGeneratorTest" PROPERTIES  _BACKTRACE_TRIPLES "D:/fdlang/CMakeLists.txt;273;add_test;D:/fdlang/CMakeLists.txt;0;")
else()
  add_test("ExecutableGeneratorTest" NOT_AVAILABLE)
endif()
